name: valorant_elo_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.1.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.0-beta.6
  cookie_jar: ^1.0.1
  cupertino_icons: ^1.0.1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  equatable: 2.0.0-nullsafety.1
  flutter_bloc: ^7.0.0-nullsafety.0
  formz: 0.4.0-nullsafety.0
  http: ^0.12.2
  meta: ^1.3.0-nullsafety.6
  path_provider: ^1.6.27
  responsive_builder: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^1.0.0-beta.6
  build_runner: ^1.10.11
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/valorant-icon.png"
